paths:
  - Applications/:
      ContentCategory: MOVIE
      ContentClassificationPegi: TWELVE_OR_MORE

save_in_db: True

filters:
  - NameFilter:
      excluded_names:
        - ".idea"
        - ".Trashes"
        - "out"
        - ".idea_modules"
        - "build"
        - "dist"
        - "lib"
        - "venv"
        - ".pyenv"
        - "python"
        - "bin"
        - "obj"
        - "debug"
        - ".git"
        - "@angular"
        - "node_modules"
        - "botocore"
        - "boto3"
        - ".terraform"
        - ".terraformrc"
        - "package"
        - "target"
        - "__pycache__"
        - "mypy_boto3_builder"
        - ".gradle"
        - ".mvn"
        - ".npm"
        - ".nvm"
        - ".npm-packages"
        - ".node-gyp"
        - ".node_repl_history"
        - ".m2"
        - ".plugins"
        - ".cache"
        - ".docker"
        - "dockervolumes"
        - "jenkins"
        - ".eclipse"
        - ".Trash"
        - ".krew"
        - "kube"
        - ".android"
        - ".bash_sessions"
        - ".sqldeveloper"
        - "Quarantine"
        - ".atom"
        - ".class"
        - ".oracle_jre_usage"
        - ".poetry"
        - ".psql_history"
        - ".pylint.d"
        - ".rnd"
        - ".vnc"
        - "bin"
        - "kubepug"
        - "Library"
        - "chromedriver"
        - "tmp"
        - "guest"
        - "@eaDir"
        - "poubelle"
        - "build"
        - ".storage"
        - ".svn"
        - "debug"
        - "release"
        - "testresults"
        - "temp"
        - "temporary_files"
        - "logs"
  - PatternFilter:
      excluded_path_pattern: "/Développement/Projets Clients/CDM/ALCRG/BDD/"
  - PatternFilter:
      excluded_path_pattern: "/TestData/"
  - PatternFilter:
      excluded_path_pattern: "/Lucene/Documentation/"
  - PatternFilter:
      excluded_path_pattern: "/DataFiles/"
  - ExtensionFilter:
      excluded_extensions:
        - "svn-base"
        - "gitattributes"
        - "uYlOfa"
        - "sublime-project"
        - "sqlite3"
        - "log"
        - "cpp_disabled_avr_specific"
        - "tmp"
        - "temp"
        - "dat"
        - "bak"
        - "db"
        - "ibd"
        - "pyc"
        - "class"
        - "jar"
        - "war"
        - "DS_Store"
        - "AppleDouble"
        - "LSOverride"
        - "tab"
        - "so"
        - "gz"
        - "tar"
        - "Folder"
        - "__styleext__"
        - "APACHE2"
        - "apk"
        - "appcache"
        - "attic"
        - "babelrc"
        - "before"
        - "bin"
        - "bnf"
        - "BSD"
        - "cache"
        - "backup"
        - "pbxproj"
        - "uuid"
        - "jbf"
        - "dump"
        - "vdproj"
        - "clonedeep"
        - "debounce"
        - "def"
        - "delivery"
        - "disabled"
        - "dist"
        - "dist - info"
        - "dmg"
        - "editorconfig"
        - "!bt"
        - "onetoc2"
        - ".com.google.Chrome"
        - "_____padding_file_"
        - "gitmodules"
        - "lock"
        - "pyc"
        - "sample"
        - "map"
        - "svn"
        - "svn-base"
        - "pdb"
        - "ldf"
        - "bup"
        - "ds_store"
        - ".ifo"
        - ".vob"
        - "_"
