version: '3.3'

services:
  db:
    build:
      context: .
    container_name: fs_crawler_db
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ./init_scripts/1.init.sql:/docker-entrypoint-initdb.d/1.init.sql
      - ./mariadb/:/var/lib/mysql/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
