version: '3.3'

services:
  db:
    build:
      context: .
    container_name: fs_crawler_db
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./init_scripts/1.init.sql:/docker-entrypoint-initdb.d/1.init.sql
      - /media/sa-nas/docker_vol_db/postgres/fs_crawler:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
